export const productActiontype={
    SET_PRODUCT:"SET_PRODUCT",
    SELECTED_PRODUCT:"SELECTED_PRODUCT",
    ROMOVE_SELECTED_PRODUCT:"ROMOVE_SELECTED_PRODUCT",
    ADD_TO_CART:'ADD_TO_CART',
    DELETE_FROM_CART:'DELETE_FROM_CART',
    CART_VALUE_INCRESE:'CART_VALUE_INCRESE',
    CART_VALUE_DESCRECE:'CART_VALUE_DESCRECE'
    
}